package GroupieTracker

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
)

type AutoGenerated struct {
	Artist struct {
		Name string `json:"name"`
		Mbid string `json:"mbid"`
		URL  string `json:"url"`
		Bio  struct {
			Links struct {
				Link struct {
					Text string `json:"#text"`
					Rel  string `json:"rel"`
					Href string `json:"href"`
				} `json:"link"`
			} `json:"links"`
			Published string `json:"published"`
			Summary   string `json:"summary"`
			Content   string `json:"content"`
		} `json:"bio"`
	} `json:"artist"`
}

func BioApi() AutoGenerated {
	var lastFm AutoGenerated
	url := "https://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist=Cher&api_key=17bdd23e8206ae1437ebf87a53c2edd8&format=json"
	response, err := http.Get(url)
	if err != nil {
		fmt.Print(err.Error())
		os.Exit(1)
	}
	responseData, err := ioutil.ReadAll(response.Body)
	if err != nil {
		log.Fatal(err)
	}

	json.Unmarshal(responseData, &lastFm)

	return lastFm
}
